name: TradePlugin
version: '${project.version}'
main: tradeplugin.tradeplugin.TradePlugin
api-version: 1.19
commands:
  trade:
    description: trade
    usage: /trade
  AddMoney:
      description: Add Money to mans
      usage: /AddMoney mans moneys

