name: TradePlugin
version: '${project.version}'
main: tradeplugin.tradeplugin.TradePlugin
depend: [ProtocolLib]
api-version: 1.19
commands:
  trade:
    description: trade
    usage: /trade
  AddMoney:
      description: Add Money to mans
      usage: /AddMoney mans moneys
  SignTest:
      description : test sign gui
      usage: /signtest thats it. no args thats too hard.

